### PR TITLE
Implemented support of 'apply-to' property for Policy object and 'federation-upstream' property for PolicyDefinition object.

### PR DESCRIPTION
**Pull request by NikGovorov**
Implemented support of 'apply-to' property for Policy object and 'federation-upstream' property for PolicyDefinition object.

### CODE REVIEW

**Comment by micdenny** [comment]
@NikGovorov thank you, can you bump the [version](https://github.com/EasyNetQ/EasyNetQ.Management.Client/blob/master/Source/Version.cs) to a non-breaking version (0.47.17)?

**Comment by NikGovorov** [comment]
@micdenny, will do right after my xmas break. Thanks.

**Comment by NikGovorov** [comment]
Done.

**Comment by NikGovorov** [comment]
Rebased.

**Comment by Pliner** [comment]
Thank you!

**Pull request merged**
