### PR TITLE
Modified ConsumerDetails and Queue classes to deserialize channel_detail when running GetQueue()

### PR DESCRIPTION
**Pull request by thisLambo**
Modified the Queue so that the ConsumerDetails property is a List of ConsumerDetail and modified ConsumerDetail to include a property ChannelDetail which includes the Connection and Channel information of a consumer.

Example JSON from queue description ("channel_details" is surrounded by the comment):
```JSON
{
 "memory" : 21960,
 "messages" : 0,
 "messages_details" : {
  "rate" : 0.0
 },
 "messages_ready" : 0,
 "messages_ready_details" : {
  "rate" : 0.0
 },
 "messages_unacknowledged" : 0,
 "messages_unacknowledged_details" : {
  "rate" : 0.0
 },
 "idle_since" : "2015-06-12 13:50:34",
 "consumer_utilisation" : "",
 "policy" : "PolicyTesting",
 "exclusive_consumer_tag" : "",
 "consumers" : 1,
 "down_slave_nodes" : "",
 "state" : "running",
 "messages_ram" : 0,
 "messages_ready_ram" : 0,
 "messages_unacknowledged_ram" : 0,
 "messages_persistent" : 0,
 "message_bytes" : 0,
 "message_bytes_ready" : 0,
 "message_bytes_unacknowledged" : 0,
 "message_bytes_ram" : 0,
 "message_bytes_persistent" : 0,
 "backing_queue_status" : {
  "q1" : 0,
  "q2" : 0,
  "delta" : ["delta", "undefined", 0, "undefined"],
  "q3" : 0,
  "q4" : 0,
  "len" : 0,
  "target_ram_count" : "infinity",
  "next_seq_id" : 0,
  "avg_ingress_rate" : 0.0,
  "avg_egress_rate" : 0.0,
  "avg_ack_ingress_rate" : 0.0,
  "avg_ack_egress_rate" : 0.0
 },
 "incoming" : [],
 "deliveries" : [],
 "consumer_details" : [{
//-----
   "channel_details" : {
    "name" : "10.1.12.46:52381 -> 10.1.12.64:5672 (4)",
    "number" : 4,
    "user" : "User",
    "connection_name" : "10.1.12.46:52381 -> 10.1.12.64:5672",
    "peer_port" : 52381,
    "peer_host" : "10.1.12.46"
   },
//-----
   "queue" : {
    "name" : "Queue1",
    "vhost" : "VHost1"
   },
   "consumer_tag" : "8a705e2b-64b5-4b98-ac9d-4f3b1671d15b",
   "exclusive" : false,
   "ack_required" : true,
   "prefetch_count" : 20,
   "arguments" : {
    "x-priority" : 0,
    "x-cancel-on-ha-failover" : false
   }
  }
 ],
 "name" : "Queue1",
 "vhost" : "VHost1",
 "durable" : true,
 "auto_delete" : false,
 "arguments" : {},
 "node" : "rabbit@DELL"
}
```

### CODE REVIEW

**Comment by Pliner** [comment]
@thisLambo 
Sorry for so long feedback, could you merge master to your branch and bump the version in Source/Version.cs?

**Comment by thisLambo** [comment]
Sure thing. It'll be a bit before I have the chance to.

**Comment by Pliner** [comment]
@thisLambo I will wait for your commits :wink:

**Comment by thisLambo** [comment]
Completed

**Comment by Pliner** [comment]
Thanks!

**Pull request merged**
