### PR TITLE
Added UsePort flag

### PR DESCRIPTION
**Pull request by BluePositive**
A potential solution for Issue #166

### CODE REVIEW

**Comment by zidad** [comment]
The thing is, hiding the port is ONLY relevant when it's 443, so making this configurable adds little extra value, and I think it's safe to assume we never have to send explicitly if it's 443

**Comment by BluePositive** [comment]
Good point

**Comment by Pliner** [comment]
Also we have https://github.com/EasyNetQ/EasyNetQ.Management.Client/issues/131, which is a bit relevant to the issue.

**Comment by BluePositive** [comment]
Right if we implement the idea described in  #131 (creating a new constructor that accepts a complete url)  it will solve this issue as well.
However, #131 looks more complicated to implement, if we focus just on the port issue it should be a smaller change. (espiscaly if we go with @zidad's idea of using port 443 as a determiner)

**Comment by BluePositive** [comment]
@zidad should I make a new pull request with your idea of using port 443 as a determiner?

**Comment by zidad** [comment]
> 

Sure! Then we can merge it. I see the other change as additional.

**Review by zidad — APPROVED** [review]

**Review by zidad — APPROVED** [review]

**Comment by zidad** [comment]
> @zidad Thanks I'm very impressed with the quick response time.

👌 thanks for the contribution!

**Pull request merged**
