### PR TITLE
Update PolicyDefinition.cs

### PR DESCRIPTION
**Pull request by refaelyehuda**
missing policy definition

### CODE REVIEW

**Comment by micdenny** [comment]
thank you, can you please also bump the [version](https://github.com/EasyNetQ/EasyNetQ.Management.Client/blob/master/Source/Version.cs) to `0.51.2.0` with a small description, thanks.

**Comment by refaelyehuda** [comment]
The version  was updated.
Thanks for your help

**Comment by zidad** [comment]
@refaelyehuda thanks a lot for the PR!

**Comment by refaelyehuda** [comment]
Are you update your Nuget with these changes?

**Comment by zidad** [comment]
@refaelyehuda Yep! It's there already: https://www.nuget.org/packages/EasyNetQ.Management.Client/0.51.2.115

**Comment by refaelyehuda** [comment]
Thanks for the fast response ☺
 ☺
2017-05-11 11:32 GMT+03:00 Wiebe Tijsma <notifications@github.com>:

**Pull request merged**
