### PR TITLE
Use Ackmode instead of Requeue

### LINKED ISSUE #62: GetMessagesFromQueue fails with "Bad Request"
RabbitMQ Server 3.7.0
EasyNetQ.Management.Client 0.51.3.116

`var messages = this.client.GetMessagesFromQueue(myQueue, new GetMessagesCriteria(1, true));`

This code fails with a "Bad Request"
When the query is run from Postman I get the reason code key_missing: ackmode
So I modify my query body from
`{"count":1,"requeue":true,"encoding":"auto"}`
(which is was EasyNetQ is sending)
to
`{"count":1,"requeue":true,"encoding":"auto","ackmode":"ack_requeue_true"}`
and then it works.

### PR DESCRIPTION
**Pull request by poteb**
Made this for #62

### CODE REVIEW

**Comment by poteb** [comment]
@micdenny I hope I did it correctly.

**Comment by micdenny** [comment]
> @micdenny I hope I did it correctly.

not really, you merged instead of rebasing and there's a typo in the commmit message `Pumped` should be `Bumped` 😄 

I'm fixing and I will push a new PR with your commits in it.

**Comment by poteb** [comment]
oops... sorry about that, thanx for fixing

**Comment by micdenny** [comment]
closed in favor of #66

**Pull request closed without merging**
