### PR TITLE
Change type of tags in List instead of CSV

### LINKED ISSUE #150: Problem with GetUser (CreateUser) with new version of RabbitMQ 3.9.x
Hi,
I'm getting an exception when fetching/creating user on the new RabbitMQ version 3.9.x using EasyNetQ.Management.Client version 1.4.0 (I have also tried older versions of the EasyNetQ.Management.Client with the same result).
It works without any problem on the latest 3.8 version (3.8.22) of RabbitMQ.

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'tags', line 1, position 159.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at EasyNetQ.Management.Client.ManagementClient.<>c__86`1.<DeserializeResponseAsync>b__86_0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyNetQ.Management.Client.ManagementClient.<CreateUserAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EasyNetQ.Management.Client.ManagementClientExtensions.CreateUser(IManagementClient source, UserInfo userInfo, CancellationToken cancellationToken)

### PR DESCRIPTION
**Pull request by Popeye4242**
fixes #150

### CODE REVIEW

**Review by micdenny — COMMENTED** [review]
I would like to advise that this will become a breaking change.

This is not a fix, the split was of course intentional, I like that? not so much... why it was developed that way? I really don't know, BTW this PR should be named "Change type of tags in List<string> instead of CSV" and then discussed if we really want to make this breaking change.

**Comment by Popeye4242** [comment]
This is intended as fix for #150

**Comment by micdenny** [comment]
> This is intended as fix for #150

ok now make sense 😄 

you can add in the description of the PR "fixes #150" so the issue will be closed when this PR will be merged

**Comment by micdenny** [comment]
Check the build error, there's something:

> C:\projects\easynetq-management-client\Source\EasyNetQ.Management.Client.IntegrationTests\ManagementClientTests.cs(81,39): error CS1061: 'StringCollectionAssertions' does not contain a definition for 'Be' and no accessible extension method 'Be' accepting a first argument of type 'StringCollectionAssertions' could be found (are you missing a using directive or an assembly reference?)

**Comment by Popeye4242** [comment]
I don't think I will be able to fix the remaining unit tests. I am not deep enough in this to fix them on my own.

**Comment by Pliner** [comment]
It has already been resolved

**Pull request closed without merging**
