### PR TITLE
Add extensions generator

### PR DESCRIPTION
**Pull request by inikulshin**
For discussion https://github.com/EasyNetQ/EasyNetQ.Management.Client/discussions/301

Add `ExtensionGenerator` project with code generator ([ISourceGenerator](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.isourcegenerator)) for `IManagementClient` extensions.

1. `ManagementClientExtensions` is renamed to `partial IManagementClientExtensions` and all trivial extensions are deleted.
2.  For each method of `IManagementClient` and `IManagementClientExtensions` generate **replacement** extensions (also in `partial IManagementClientExtensions`):
	1. Same method name.
	2. Same return type.
	3. Replaced parameters.
	4. E.g. methods with `string vhostName` parameter are extended with methods with `Vhost vhost` parameter instead.
3. For each method of `IManagementClient`, `IManagementClientExtensions` (including generated code) generate **sync** extensions (also in `partial IManagementClientExtensions`):
	1.  Method name is w/o `Async` suffix.
	2. Return type is `void`/generic parameter of `Task<>`. (the return type of `.GetAwaiter().GetResult()`)
	3. Same parameters.
	4. E.g. method `Task<Overview> GetOverviewAsync(CancellationToken cancellationToken = default)` is extended with `Overview GetOverview(this IManagementClient client, CancellationToken cancellationToken = default) => client.GetOverviewAsync(cancellationToken).GetAwaiter().GetResult();`

Also fixes https://github.com/EasyNetQ/EasyNetQ.Management.Client/issues/257.

### CODE REVIEW

**Comment by inikulshin** [comment]
I'm not sure about leading `I` in names of `IManagementClient` extension classes.

I used it because I'm was more confused by the fact that `ManagementClientExtensions` does not extend `ManagementClient` class, than by having `I` prefix for class with 'Extensions' suffix.

**Comment by zidad** [comment]
Nice work on the generators! 

However, my personal preference is still to make the whole library async-first and async-only, I think this will be the way forward for every .NET library in the long run, sync versions are there only for backwards compatibility and preferably should not be used anymore at all.

If you really want the sync versions let's get rid of the complexity here and create a separate package for that, like EasyNetQ.Management.Client.SyncExtensions or something like that.

@Pliner @micdenny what do you think?

**Comment by inikulshin** [comment]
@zidad there is no too many additional complexity in generation sync extensions, only `SyncGenerator.cs` that is very similar to `ReplacementGenerator.cs`.

But I don't mind moving sync extensions to a separate package.

**Review by zidad — APPROVED** [review]

**Comment by inikulshin** [comment]
@zidad thanks. Is PR intentionally not merged?

**Comment by zidad** [comment]
> @zidad thanks. Is PR intentionally not merged?

It's a pretty fundamental change, would really like @Pliner or @micdenny to chip in, if they don't respond I'll merge tomorrow ok?

**Comment by zidad** [comment]
@inikulshin looks like the package failed to publish, probably it will not work without this dependency?

**Comment by zidad** [comment]
To fix I would probably still prefer to have it:
- all 1 assembly so we don't introduce Generators as a dependency
- or move it to a completely separate package while reversing the dependency (Generators can depend on Management.Client but not the other way around). 

I'm not sure why it's not getting the version number correct.

**Comment by zidad** [comment]
https://github.com/EasyNetQ/EasyNetQ.Management.Client/pull/311

**Pull request merged**
