### PR TITLE
Chage user model Tags to be a list

### PR DESCRIPTION
**Pull request by Tychus**
Change the model of User to use a list of string instead of a single string for Tags.
RabbitMq api returns a list of tags instead of comma separated values

### CODE REVIEW

**Comment by Tychus** [comment]
Working on fixing the broken tests. Hopefully get this going asap otherwise the package is not usable.

**Comment by Tychus** [comment]
``` Failed EasyNetQ.Management.Client.IntegrationTests.ManagementClientTests.Should_be_able_to_delete_a_user [11 ms]
  Error Message:
   Newtonsoft.Json.JsonSerializationException : Error converting value "monitoring,management" to type 'System.Collections.Generic.IList`1[System.String]'. Path 'tags', line 1, position 166.
---- System.ArgumentException : Could not cast or convert from Sys`

Quickly going through the reports i noticed that the returned tags are actually CSVs what version of RMQ is running on docker ? Perhaps this is not as easy to fix as i thought since we'd want it to work for all versions. Any ideas ?

**Comment by sungam3r** [comment]
> Perhaps this is not as easy to fix as i thought since we'd want it to work for all versions. Any ideas ?

Bump major version and add note about that breaking change in readme.

**Comment by Tychus** [comment]
> Bump major version and add note about that breaking change in readme.

Yes but have to make the integration tests work first they are running against an older version of rabbit it seems.

**Comment by kmatyaszek** [comment]
I have already resolved this issue in #153. It works with new and older version of RabbitMQ.

**Pull request closed without merging**
