### PR TITLE
Migrates project to .NET Core

### PR DESCRIPTION
**Pull request by conniey**
* Removes defined NETFX and NET_STANDARD directives
   * [Compiler directives are predefined](https://github.com/dotnet/core-docs/blob/master/docs/core/tutorials/libraries.md#how-to-multitarget) for .NET Core projects
* Moves from [WebRequest to HttpClient](http://stackoverflow.com/questions/22214930/httpclient-vs-httpwebrequest)
   * HttpClient can perform multiple asynchronous requests and works on newer platforms
* Fixes AppVeyor build
* Migrates test projects to xproj
   * makes it easier to reference other library projects
   * would allow for using dotnet test with [nunit](https://github.com/nunit/dotnet-test-nunit)

### CODE REVIEW

**Comment by micdenny** [comment]
we used NETFX to have a family for full .net fx instead of specific framework version, because many codes are not specific to a fx version, but maybe we missed how the predefined directive works... if I use NET40 this directive will be exposed even if I compiled against fx 4.5/4.5.1?

**Comment by zidad** [comment]
Quite a nice PR! I kind of liked the NETFX conditional too though to not have to specify specific framework versions in code.

**Comment by conniey** [comment]
> we used NETFX to have a family for full .net fx instead of specific framework version, because many codes are not specific to a fx version, but maybe we missed how the predefined directive works... if I use NET40 will this directive be exposed even if I'm compiling against fx 4.5/4.5.1?

Good points. I reverted those changes. :)

**Comment by micdenny** [comment]
this PR is connected to #34

**Comment by zidad** [comment]
@conniey great! @micdenny shall we merge this to the work in progress branch? I'm ok with NUnit instead of XUnit if that works with .NET too?

**Comment by micdenny** [comment]
> @micdenny shall we merge this to the work in progress branch?

I would like to review it in local before merge it, please be patient, and feel free to ping me back next week if I didn't closed/merged this.

> I'm ok with NUnit instead of XUnit if that works with .NET Core too?

I would prefer xunit because at the moment is the standard testing framework on all the net core foundation, **but** If we can preserve nunit in this first instance is a sure GO for me, because we can focus on porting ENQ to core, then we can make fancy stuff 😄 

we should also tell this on https://github.com/EasyNetQ/EasyNetQ/issues/508 because @DustinVenegas is trying to convert all in xunit.

**Pull request merged**
