### PR TITLE
RabbitMq 3.7.0 Forward Compatibility Fix

### PR DESCRIPTION
**Pull request by StevenBonePgh**
PUT responses now use 201 Created (under Cowboy - 3.7.0+) instead of 204 No Content (WebMachine - pre 3.7.0)

### CODE REVIEW

**Comment by zidad** [comment]
@StevenBonePgh Thanks a lot for the PR! 

Do you know if this is a future-proof fix for when 3.7.0 is released? It would still be required to have the 'cowboy' header, if not this fix will break, or do I see this wrong?

Do you know if there's a way to check for a version range instead of the cowboy header maybe?

@micdenny  @Pliner any ideas?

**Comment by micdenny** [comment]
What about wait the release of new version 3.7.0 and only support the header that it is needed for?

**Comment by zidad** [comment]
@micdenny exactly

**Comment by StevenBonePgh** [comment]
@micdenny, @zidad : I don't believe only supporting one is a good idea.  Personally, I have very little control over what version of Rabbit I am connected to.  Furthermore, if there is a security patch to RabbitMQ that customers insist on using, I don't want and should not need to rev my code.  This also breaks the philosophy of forwards compatibility of the AMQP protocol and EasyNetQ in general.

@zidad: There is a way to detect version but that would involve making another management call to determine.  If the management client is new'd, used for a put, and out of scoped frequently, this would be potentially significant unnecessary overhead.  Sure you can make a static (or instance) flag to indicate the version or behavior of PUTs, but when do you 'refresh' this value?  Surely it is possible to upgrade Rabbit while code is otherwise running which would break it until client code is restarted.  Or worse yet, with a static, if you were talking to multiple management instances with different versions this approach will not work.

The initial approach I thought of was to accept both 201 and 204 as valid, but it is then possible that we hide a PUT failure on Cowboy.  I have not hit a case where this was true in initial testing, but I would not wish to risk burying a true and valid error with a PUT from the caller client code.

An alternative approach that I am now leaning towards based on @zidad's comment about the 'Cowboy' header is to assume that a "201 Created" is always good (and don't check header for server) which is the desired/expected REST behavior on a PUT anyway.  If a "204 No Content" is received, we then look at the header and not throw if it is a WebMachine based server.  The assumption here is that all supported versions of Rabbit have WebMachine in the server header which appears to be a valid assumption.

Thoughts?

**Comment by zidad** [comment]
@StevenBonePgh Actually lean towards your initial approach, I like the (simplest) idea of just accepting 201 and 204 as valid the most. I think (hope) we can assume there will never be a 204 response on failure in older versions, how else would you be able to distinguish between failure and success?

**Comment by micdenny** [comment]
> I have very little control over what version of Rabbit I am connected to

At the first shot I didn't get that this changes was related to a changed at **SERVER ** side and not regarding the `RabbitMQ.Client`, so now it's clear your intent, sorry!

We definitely need a forward compatibility fix :smile: so let's discuss that ;)

**Comment by micdenny** [comment]
> An alternative approach that I am now leaning towards based on @zidad's comment about the 'Cowboy' header is to assume that a "201 Created" is always good (and don't check header for server)

@StevenBonePgh this could be nice, in fact the error we are returning is `UnexpectedHttpStatusCodeException` and we could treat everything that is not 201 as an unexpected status code isn't it? 

In detail I was checking how was the code in the .net fx about `HttpResponseMessage.EnsureSuccessStatusCode()` and they check this:

```csharp
        public bool IsSuccessStatusCode
        {
            [__DynamicallyInvokable]
            get
            {
                if (this.statusCode < HttpStatusCode.OK)
                {
                    return false;
                }
                return (int)this.statusCode <= 299;
            }
        }
```

**Comment by StevenBonePgh** [comment]
Based on [this SO Answer](http://stackoverflow.com/questions/797834/should-a-restful-put-operation-return-something) and reading the spec as referenced and a few other resources, perhaps the best fix is to accept 200, 201, and 204 as the 'expected' codes for a PUT.  Then we don't need to worry about the Rabbit server version.  If that is acceptable, I'll update the PR.

**Comment by zidad** [comment]
@StevenBonePgh :+1:

**Comment by micdenny** [comment]
ok good, thanks guys, going to merge it now!

**Pull request merged**
