### PR TITLE
adding Partition model and Node.Partitions prop

### PR DESCRIPTION
**Pull request by ryanchappell**
Context:
https://groups.google.com/forum/#!msg/easynetq/vXLOR8NelSo/KJ7zePoNVH0J

### CODE REVIEW

**Comment by Pliner** [comment]
@ryanchappell Thank you for contribution.

Could you bump the version in Version.cs?

**Comment by Pliner** [comment]
@ryanchappell Also could you explain why Partition class is empty?

**Comment by ryanchappell** [comment]
Yup, I'll bump the version.

It is empty because I do not know the schema of the partition property coming back from the response. Michael pointed out that this documentation is not published, so I left it empty. 

"We don't really document management plugin changes in such depth. A quick look 
at rabbit_node_monitor suggests partition stats emission has been around for a long time."

https://groups.google.com/d/msg/easynetq/vXLOR8NelSo/WOsTgz1RsBQJ

For our current use case, we merely need to know if the partitions count is greater than 0.

**Comment by Pliner** [comment]
@ryanchappell, thank you for clarification.

PS It will be very nice if partition model will become more complete :smile:

**Comment by ryanchappell** [comment]
@Pliner, totally! If I find more of the schema, I'll definitely add it :) Thanks for the merge!

**Pull request merged**
