### PR TITLE
New method for getting detailed queue stats

### PR DESCRIPTION
**Pull request by zidad**
Update for PR https://github.com/EasyNetQ/EasyNetQ.Management.Client/pull/26

### CODE REVIEW

**Comment by micdenny** [comment]
is this a squashed PR for #26 or you added some other features?

**Comment by zidad** [comment]
@micdenny jup It's just a squashed PR and version.cs conflict resolved...

**Comment by andlju** [comment]
Looks good to me!

**Comment by zidad** [comment]
@andlju merged, thanks for a great addition!

**Pull request merged**
