### PR TITLE
Support deleting exchange to exchange bindings

### PR DESCRIPTION
**Pull request by joostas**
I updated DeleteBinding method on feature/netcore branch. Added Xunit tests instead of NUnit.
I am not sure if these actions are exactly what @micdenny asked for me.

### CODE REVIEW

**Comment by zidad** [comment]
Thanks! would you mind rebasing on top of master and updating the version.cs?

**Comment by micdenny** [comment]
@joostas there were a github issue related to this PR or a google group discussion? sorry I forgot about it 😞

**Comment by micdenny** [comment]
ok this is releated to the #46 and issue #43

**Comment by micdenny** [comment]
we did some messing-up to the code base with netcore porting, so I need to move this PR to `master` that now contains netcore

**Comment by luigiberrettini** [comment]
Superseded by #73

**Pull request closed without merging**
