### PR TITLE
Convert to .NET Core

### LINKED ISSUE #34: Convert to .NET Core
connected to https://github.com/EasyNetQ/EasyNetQ/issues/508 and the PR https://github.com/EasyNetQ/EasyNetQ/pull/606

### PR DESCRIPTION
**Pull request by micdenny**

### CODE REVIEW

**Comment by micdenny** [comment]
pushed pre-release package on myget, but it works only for fx451, because net core has issue to fix, check the TODOs

**Comment by conniey** [comment]
@micdenny @zidad Is there anything left to do for this?  

The reason `continuous-integration/appveyor/branch` CI build is failing is because the following lines are pointing to my MyGet feed rather than the easynetq-unstable one.  

1. Modify [appveyor.yml: L28 - L30](https://github.com/EasyNetQ/EasyNetQ.Management.Client/blob/feature/netcore/appveyor.yml#L28-L30)
   * Change `server`
   * Change `api_key: secure` with MyGet API key.  Encrypt the key using [AppVeyor Encryption Tool](https://www.appveyor.com/docs/deployment/nuget/)

Output that is failing in CI build:

```
"NuGet" deployment for branch "master" has been skipped because current branch is "feature/netcore"
Deploying using NuGet provider
Publishing EasyNetQ.Management.Client.2.0.0-netcore1185.nupkg to https://www.myget.org/F/easynetq-tester/api/v2/package...
Error publishing package. NuGet server returned 403: Forbidden
```

**Comment by micdenny** [comment]
@zidad what do you think is this `gitversion` error while building?

image

**Comment by zidad** [comment]
It looks like AppVeyor is checking out a commit ID instead of a branch/tag. GitVersion depends on the current branch name so it can't generate a proper version number now. Let me see if I can find some info on this.

**Comment by micdenny** [comment]
it's strange because in other repo I don't have this problem with PRs

**Comment by micdenny** [comment]
ok probably I don't have problems because of this:

https://github.com/RadicalFx/Radical/blob/develop/GitVersionConfig.yaml#L4

```yaml
branches:
  develop:
    tag: alpha
    prevent-increment-of-merged-branch-version: true
```

**Comment by lsfera** [comment]
Any news on this?

**Comment by zidad** [comment]
I have no opportunity to work on this, as I have to do it in my spare time. However feel free to submit a PR if you need it soon.

**Comment by micdenny** [comment]
closed in favor of #60

**Pull request closed without merging**
