### PR TITLE
Added GetChannelsAsync overload that takes the connection.

### PR DESCRIPTION
**Pull request by mikehadlow**
Added GetChannelsAsync overload that takes the connection. 
Uses the API endpoint /connections/name/channels.

### CODE REVIEW

**Comment by mikehadlow** [comment]
@zidad or @micdenny OK to merge this?

**Comment by mikehadlow** [comment]
@zidad, I notice that you guys are doing things properly now with numbered releases. What would be the process for getting these changes into a new release?

**Comment by zidad** [comment]
@luigiberrettini did a lot of work setting it up, I'm not 100% sure if it works now, there still was a small problem with passing the new version number in the package version, but it should build and release automatically with a new stable version number, if not, we need to fix it...

**Comment by luigiberrettini** [comment]
Hi @mikehadlow I am not sure I understood your question, but PR merge is not tied to new releases:
to create a new release it is sufficient to create a GitHub release and the tag indicating the version will be the trigger for AppVeyor to publish a NuGet package with that version number.

**Comment by mikehadlow** [comment]
Hi @luigiberrettini, Thanks, that makes sense. I'll try it.

**Comment by mikehadlow** [comment]
Hi @luigiberrettini. I tried creating a new release, but the AppVeyor process seems to have failed?

**Comment by luigiberrettini** [comment]
It is strange to me that you do not belong to the repo teams or collaborator but you are able to create a release

**Comment by luigiberrettini** [comment]
Anyway looking at the build the error is due to the non renewed NuGet API key:
`The specified API key is invalid, has expired, or does not have permission to access the specified package.`

Please open another issue to track this task that needs to be done

**Comment by mikehadlow** [comment]
Thanks @luigiberrettini, I've added issue NuGet API key has expired #123 to track this. 

As for how I have permission to create release, maybe it's because I'm an owner of EasyNetQ organisation? I don't really know how permissions are inherited in GitHub though.

**Comment by luigiberrettini** [comment]
> maybe it's because I'm an owner of EasyNetQ organisation

Sure I didn't look at that list: if you are an org owner you are like root in Linux 😛

**Comment by luigiberrettini** [comment]
To build now you should remove the tag and recreate it (via git or deleting and recreating the release)

**Comment by mikehadlow** [comment]
Hi @luigiberrettini, Just tried deleting and recreating the release, but the AppVeyor build has failed again.  How do you view the logs?
Thanks for all your help with this BTW.

**Comment by luigiberrettini** [comment]
If you look at [commits](https://github.com/EasyNetQ/EasyNetQ.Management.Client/commits/master) you can find an icon showing if the build was successful or not and hovering on it it displays more details (including the links to the build log).

**Comment by mikehadlow** [comment]
Thanks. Looks like it's a failing test. I'll investigate.

**Comment by mikehadlow** [comment]
Hmm, test works fine locally. Seems to be a flaky connection on the build machine. I'll try to trigger it again.

**Pull request merged**
