### PR TITLE
sanitise source/destination names in DeleteBindingAsync

### PR DESCRIPTION
**Pull request by mijabr**
allow characters + # / :  in queue/exchange names when deleting bindings

### CODE REVIEW

**Comment by bebematley** [comment]
Hello,

I have solved this issue with method UrlEncode of the System.Net

**Name = WebUtility.UrlEncode (queue.Name);**

In this way I correctly codify any special character,
I have already used in my prod enviroment for sanitise it, befoure to call DeleteQueue

**Comment by micdenny** [comment]
`WebUtility` is present in [.netstandard 1.5](https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility?view=netstandard-1.5) and [netfx 4.5.2](https://docs.microsoft.com/en-us/dotnet/api/system.net.webutility?view=netframework-4.5.2) so I think would be great to use it and fix all possible characters.

what do you think @mijabr @zidad ?

**Comment by zidad** [comment]
@micdenny for sure that seems like the best solution!

**Comment by micdenny** [comment]
> WebUtility.UrlEncode(....);

@mijabr can you apply that method instead of all the replace?

**Comment by micdenny** [comment]
@mijabr can we do this for all the methods? so we cover all the management api

**Comment by mijabr** [comment]
I'm unable reproduce the original issue with the integration tests. I'll have to go back and dig deeper.

**Comment by micdenny** [comment]
> I'm unable reproduce the original issue with the integration tests. I'll have to go back and dig deeper.

ok no pressure, take your time 😄 but I would like to spread this fix for all the methods so to close this something like forever, because this issue was fired different times in the past, so it's time to really fix this ;)

**Comment by micdenny** [comment]
maybe `SanitiseName` is already used everywhere? BTW just check that this fix has been spread whenever is needed, thanks 🙇

**Comment by micdenny** [comment]
@mijabr do you have time to implement this using `WebUtility.UrlEncode(....);` instead of `SanitiseName(...)`?

**Comment by Pliner** [comment]
Fixed in #171

**Pull request closed without merging**
